apiVersion: v1
kind: Service
metadata:
  labels:
    app: bite-auth-api
  name: bite-auth-api-srv
spec:
  selector:
    app: bite-auth-api
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}